project:
  type: website
  output-dir: docs 

website:
  title: "Mackenzie Eckles ePortfolio"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About Me"
      - href: process.qmd
        text: "Part 1 - Describe your Process"
      - href: final.qmd
        text: "Final Portfolio"

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true

editor: source